services:
  db:
    image: mysql:5.6
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "ifilmes"
    ports:
      - 3306:3306

  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --requirepass redispw'
    ports:
      - 6379:6379

  app:
    container_name: app
    build: ./ifilmes-api/
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
      - redis-server
      - app-auth

  app-auth:
    container_name: app-auth
    build: ./auth-api/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis-server
